name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Baixar o repositório
      - uses: actions/checkout@v3

      # Passo 2: Gerar a animação de cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Marcellecarol # Nome de usuário atualizado
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Passo 3: Configurar o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
